### PR TITLE
Fixes and additional functions

### PR DESCRIPTION
**Pull request by kuz-z-zma**
- Fixed Feed URL
- Added more detailed description for Flickr User ID and where to find it
- Fixed typos and inconsistent capitalization
- Added separate URL and Title functions for use in themes

### CODE REVIEW

**Comment by acrylian** [comment]
Thanks for your contributions. I originally made this for a client whithout ever having used Flickr myself. A few notes:

- Thanks for the case changes like flickrfeed -> flickrFeed. That's of course cosmentic since only variables are case senstive.
- You changes some backticks in docblocks to semmicolons. The backticks are on purpose, those are markdown formatting for inline code. We use that also in main ZP because it is better readable and also our doc generator uses that.
- I am not so sure the two new function add benefit because they just return the plain value you can easily  get via the array index of the array as well. Especially since you need to pass that array first anyway.

**Comment by kuz-z-zma** [comment]
> flickrfeed -> flickrFeed. That's of course cosmentic since only variables are case senstive.

It helps to differentiate easily between functions and keys for options, improves readability.

>You changes some backticks in docblocks to semmicolons. The backticks are on purpose, those are markdown formatting for inline code. We use that also in main ZP because it is better readable and also our doc generator uses that.

I'm obviously not attached to this change - I don't think I saw them used as such for any Zenphoto plugins I've dealt with (code is just pasted as is in commented portion with plugin info) and since this does nothing for formatting when viewing plugin info in backend - never occurred to me to suspect their purpose. Where can I check the markdown documentation for that? 

>I am not so sure the two new function add benefit because they just return the plain value you can easily get via the array index of the array as well. Especially since you need to pass that array first anyway.

I wanted an easy way to construct output for the theme without Image preview - for custom headers, display of description etc.
pubDate is extracted like this, so why not URL and Title

**Comment by kuz-z-zma** [comment]
Rolled back backticks and added some clean-up to the getItemLinkAndThumb output, as it produced an empty `<p></p>` as of now.

**Comment by acrylian** [comment]
> It helps to differentiate easily between functions and keys for options, improves readability.

Yes , of course

> Where can I check the markdown documentation for that?

Well, third party plugins are of course not use for our general doc. zenphoto does not have it consistently for historic reasons but whenever we change things we primarily use markdown. 

It's a clean formatting even readable without processing. GitHub has a documentation: https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

> pubDate is extracted like this, so why not URL and Title

I added primarily functions only if the value requires some processing like pubDate does. No big deal otherwise to keep them.

**Pull request merged**
